apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-sentinel-db
  namespace: cloud-sentinel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi
